# Generated by Django 3.2.9 on 2022-01-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messages_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='roomName',
        ),
    ]
