# Generated by Django 3.2.9 on 2022-01-03 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_messages_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='roomName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
    ]
