# Generated by Django 3.2.9 on 2022-01-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_messages_roomname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='roomName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
    ]
